basePath: /
definitions:
  models.File:
    properties:
      cachedUrl:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost
info:
  contact:
    email: brandenmorin14@gmail.com
    name: Branden Morin
  description: This is a server for uploading and downloading files.
  title: Files API
  version: "1.0"
paths:
  /Files:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.File'
            type: array
      summary: Retrieves all Files
  /files:
    post:
      parameters:
      - description: Title
        in: formData
        name: title
        required: true
        type: string
      - description: Content
        in: formData
        name: content
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.File'
      summary: Creates an File
  /files/{id}:
    delete:
      parameters:
      - description: File ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.File'
      summary: Deletes a File based on given ID
  /files/{name}:
    get:
      parameters:
      - description: File Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.File'
      summary: Retrieves a File based on given Name
  /getpresigned:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Gets a presigned URL for uploading a file to GCS
swagger: "2.0"
